services:
  image_server:
    build: .
    container_name: image_server
    ports:
      - "8099:8099"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${IMAGE_SERVER_DATA_ROOT}/certs:/certs:ro
      - ${IMAGE_SERVER_DATA_ROOT}/data:/data
      - ${IMAGE_SERVER_DATA_ROOT}/images:/images
      - ${IMAGE_SERVER_DATA_ROOT}/log:/log
    restart: always

    environment:
      - TZ=Europe/Moscow
